# Numpy_Assignment-02

## Practical Questions

In [1]:
#Question_No.1:Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its
#rows and columns.

#Answer:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
random_array = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose the array)
transposed_array = random_array.T

# Print the original and transposed arrays
print("Original Array:")
print(random_array)

print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[33 85 89]
 [65  4 16]
 [37 51 94]]

Transposed Array:
[[33 65 37]
 [85  4 51]
 [89 16 94]]


In [3]:
#Question_No.2:Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2
#array

#Answer:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(1, 11)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

# Print the arrays
print("Original 1D Array:")
print(array_1d)

print("\nReshaped to 2x5 Array:")
print(array_2x5)

print("\nReshaped to 5x2 Array:")
print(array_5x2)

Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped to 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped to 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [4]:
#Question_No.3:Create a 4x4 NumPy array with random float values. Add a border of zeros around it, 
#resulting in a 6x6 array.


#Answer:
import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.random((4, 4))

# Add a border of zeros around it, resulting in a 6x6 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the original and the array with a border
print("Original 4x4 Array:")
print(array_4x4)

print("\nArray with Border (6x6):")
print(array_with_border)

Original 4x4 Array:
[[0.30399251 0.15584347 0.93200174 0.61876431]
 [0.70481437 0.45541719 0.6623513  0.36758837]
 [0.67276076 0.91935487 0.28652395 0.02244054]
 [0.96745155 0.58201989 0.61857972 0.5509895 ]]

Array with Border (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.30399251 0.15584347 0.93200174 0.61876431 0.        ]
 [0.         0.70481437 0.45541719 0.6623513  0.36758837 0.        ]
 [0.         0.67276076 0.91935487 0.28652395 0.02244054 0.        ]
 [0.         0.96745155 0.58201989 0.61857972 0.5509895  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [5]:
#Question_No.4:Using NumPy, create an array of integers from 10 to 60 with a step of 5.


#Answer:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

# Print the array
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


In [6]:
#Question_No.5:Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case 
#transformations uppercase, lowercase, title case, etc.) to each element.

#Answer:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(array)
lowercase = np.char.lower(array)
title_case = np.char.title(array)
capitalize = np.char.capitalize(array)

# Print the results
print("Original Array:")
print(array)

print("\nUppercase:")
print(uppercase)

print("\nLowercase:")
print(lowercase)

print("\nTitle Case:")
print(title_case)

print("\nCapitalize:")
print(capitalize)

Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalize:
['Python' 'Numpy' 'Pandas']


In [8]:
#Question_No.6:Generate a NumPy array of words. Insert a space between each character of every word in
#the array


#Answer:
import numpy as np

# Generate a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words_array)

# Print the original and transformed arrays
print("Original Array of Words:")
print(words_array)

print("\nArray with Spaces Between Characters:")
print(spaced_words)

import numpy as np

# Generate a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words_array)

# Print the original and transformed arrays
print("Original Array of Words:")
print(words_array)

print("\nArray with Spaces Between Characters:")
print(spaced_words)

Original Array of Words:
['python' 'numpy' 'pandas']

Array with Spaces Between Characters:
['p y t h o n' 'n u m p y' 'p a n d a s']
Original Array of Words:
['python' 'numpy' 'pandas']

Array with Spaces Between Characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


In [9]:
#Question_No.7:Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication
#, and division.


#Answer:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition_result = array1 + array2

# Element-wise subtraction
subtraction_result = array1 - array2

# Element-wise multiplication
multiplication_result = array1 * array2

# Element-wise division
division_result = array1 / array2

# Print the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition_result)

print("\nElement-wise Subtraction:")
print(subtraction_result)

print("\nElement-wise Multiplication:")
print(multiplication_result)

print("\nElement-wise Division:")
print(division_result)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [10]:
#Question_No.8:Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


#Answer:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the identity matrix and its diagonal elements
print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [11]:
#Question_No.9:Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all 
#prime numbers in this array


#Answer:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

# Print the original array and the prime numbers found
print("Original Array:")
print(random_array)

print("\nPrime Numbers in the Array:")
print(prime_numbers)

Original Array:
[230 605 564 459 273 339 376 628 442 407 306 964 139 560 331 907 619 219
 756 627  42 810 236 814 338 457 834 225 259  29 456 711 233 107 631  59
 844 211 823 995 975 500 759 434 168  16 938 596 693 937 255 425 795 590
 589  35 821 601 845 562 814 330 285  56 562 827 440 918 213 864  60 438
 745 483 768 940  53 790 279 994 689 236 498  77  68 343 533 916 134 673
 731 901  26 123  84 378 682 546 702 992]

Prime Numbers in the Array:
[np.int64(139), np.int64(331), np.int64(907), np.int64(619), np.int64(457), np.int64(29), np.int64(233), np.int64(107), np.int64(631), np.int64(59), np.int64(211), np.int64(823), np.int64(937), np.int64(821), np.int64(601), np.int64(827), np.int64(53), np.int64(673)]


In [13]:
#Question_No.10:Create a NumPy array representing daily temperatures for a month. Calculate and display 
#the weekly averages.


#Answer:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (28 days)
daily_temperatures = np.random.randint(15, 35, size=28)  # Random temperatures between 15 and 35

# Reshape the array to represent weeks (4 weeks of 7 days each)
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Calculate weekly averages
weekly_averages = weekly_temperatures.mean(axis=1)

# Print the daily temperatures and weekly averages
print("Daily Temperatures for the Month:")
print(daily_temperatures)

print("\nWeekly Temperatures (4 weeks of 7 days each):")
print(weekly_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)

Daily Temperatures for the Month:
[25 26 25 23 28 15 22 28 16 28 18 25 17 30 17 17 20 31 32 25 20 27 17 32
 22 31 32 23]

Weekly Temperatures (4 weeks of 7 days each):
[[25 26 25 23 28 15 22]
 [28 16 28 18 25 17 30]
 [17 17 20 31 32 25 20]
 [27 17 32 22 31 32 23]]

Weekly Averages:
[23.42857143 23.14285714 23.14285714 26.28571429]
